"""Export SegFormer-B0 (ADE20K, 150 classes) to an ExecuTorch .pte (XNNPACK, fp32).

Names what depth can only measure: wall, door, stairs, window... (docs/decisions.md
2026-09-27). Same contract as the depth model, through
SemanticSegmentationModule.fromCustomModel:
  input  float32 [1,3,S,S]   RGB in [0,1], ImageNet mean/std applied by the runtime
  output float32 [1,150,S/4,S/4] logits, one channel per ADE20K class

Also writes src/ade20kLabels.ts, the label map in model order.

Licence: NVIDIA Source Code License, non-commercial (research/evaluation) only.

Usage (needs the export venv from docs/decisions.md 2026-09-26):
  PATH=$VENV/bin:$PATH python scripts/export_segformer.py 256
"""
import re
import sys

import torch
from executorch.backends.xnnpack.partition.xnnpack_partitioner import XnnpackPartitioner
from executorch.exir import to_edge_transform_and_lower
from transformers import SegformerForSemanticSegmentation

SIZE = int(sys.argv[1]) if len(sys.argv) > 1 else 256
OUT = sys.argv[2] if len(sys.argv) > 2 else f"assets/models/segformer_b0_ade20k_{SIZE}.pte"
REPO = "nvidia/segformer-b0-finetuned-ade-512-512"


class Logits(torch.nn.Module):
    def __init__(self, m):
        super().__init__()
        self.m = m

    def forward(self, x):
        return self.m(pixel_values=x).logits  # [1,150,S/4,S/4]


hf = SegformerForSemanticSegmentation.from_pretrained(REPO).eval()
model = Logits(hf).eval()
example = (torch.rand(1, 3, SIZE, SIZE),)
with torch.no_grad():
    ref = model(*example)
print("eager output", tuple(ref.shape))

ep = torch.export.export(model, example, strict=False)
prog = to_edge_transform_and_lower(ep, partitioner=[XnnpackPartitioner()]).to_executorch()
with open(OUT, "wb") as f:
    f.write(prog.buffer)
print("wrote", OUT, round(len(prog.buffer) / 1e6, 1), "MB")

# Label map, in channel order. Keys must be valid identifiers for the TS object.
names = [hf.config.id2label[i] for i in range(hf.config.num_labels)]
keys = [re.sub(r"[^A-Z0-9]+", "_", n.split(",")[0].strip().upper()).strip("_") for n in names]
seen = {}
for i, k in enumerate(keys):  # ADE20K has a few duplicate first names
    if k in seen:
        keys[i] = f"{k}_{i}"
    seen[k] = i
with open("src/ade20kLabels.ts", "w") as f:
    f.write("// Generated by scripts/export_segformer.py from the model's id2label. Do not edit.\n")
    f.write("// ADE20K class index -> key, in SegFormer's output channel order.\n")
    f.write("export const ADE20K = {\n")
    for i, k in enumerate(keys):
        f.write(f"  {k}: {i},\n")
    f.write("} as const\n\n")
    f.write("/** Human names, same order, for speech. */\n")
    f.write("export const ADE20K_NAMES: readonly string[] = [\n")
    for n in names:
        f.write(f"  {n.split(',')[0].strip()!r},\n".replace("'", '"'))
    f.write("]\n")
print("wrote src/ade20kLabels.ts,", len(keys), "classes")
